---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palcloud-app
  labels:
    app: palcloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palcloud-app
  template:
    metadata:
      labels:
        app: palcloud-app
    spec:
      containers:
      - name: palcloud-container
        image: 970547349693.dkr.ecr.us-east-2.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
